name: .NET Build

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore
      run: dotnet restore Assignment.sln

    - name: Build
      run: dotnet build Assignment.sln --no-restore

    - name: Run
      run: dotnet run --project Assignment.csproj

